### ISSUE TITLE
添加不合法题目后（如P0 # qwq）无法删除

### ISSUE THREAD

**Issue by henrytbtrue** [Anguei/Luogu-Super-Todolist#10]
RT

给一个图：

![](https://imgchr.com/i/ksZgN6)

**Comment by henrytbtrue** [comment]
emm图炸了

**Comment by henrytbtrue** [comment]
![](https://i.loli.net/2019/02/16/5c67bbc5a197b.png)

**Comment by Anguei** [comment]
> RT
> 
> 给一个图：
> 
> ![](https://camo.githubusercontent.com/74e2f18a9cba8307827afdf748f07312099244cc/68747470733a2f2f696d676368722e636f6d2f692f6b735a674e36)

感谢提醒。

已修复。
