### ISSUE TITLE
比赛中添加在用户题库中的题目,赛后被加入公开题库导致无法删除.

### ISSUE THREAD

**Issue by hehelego** [Anguei/Luogu-Super-Todolist#11]
参加某公开赛时.我添加了几个比赛题目到todolist.然而比赛结束,题目加入公开题库后.我没有办法删除这些题目了.

尝试使用脚本提供的导入计划也没能成功删除.

(~~emm,等我放个图上来好了~~

**Comment by Anguei** [comment]
> 参加某公开赛时.我添加了几个比赛题目到todolist.然而比赛结束,题目加入公开题库后.我没有办法删除这些题目了.
> 
> 尝试使用脚本提供的导入计划也没能成功删除.
> 
> (emm,等我放个图上来好了

感谢反馈。我会把导入导出功能改为编辑。

**Comment by hehelego** [comment]
orz and thx.  

~~咕咕咕?先close好了2333~~
