### ISSUE TITLE
禁用脚本后修改原任务计划列表，再重新启用，导致列表不同步

### ISSUE THREAD

**Issue by Xeonacid** [Anguei/Luogu-Super-Todolist#9]
RT
个人没想到什么太好的解决方案，油猴没有给出一个在启用/第一次运行/禁用脚本时执行代码的接口
要不在README或console什么的提示一下？xd

**Comment by Anguei** [comment]
> RT
> 个人没想到什么太好的解决方案，油猴没有给出一个在启用/第一次运行/禁用脚本时执行代码的接口
> 要不在README或console什么的提示一下？xd

感谢反馈。我会考虑每天第一次运行时强制检查同步的解决方案。

**Comment by Anguei** [comment]
已修改为每天第一次运行时强制检查同步。
